### ISSUE TITLE
[Feature] Support for OAuth

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/ngx-ytd-api#18]
There's currently no support for certain API options as of now due to a lack of OAuth capabilities.

# TODO

- [x] **Decide on whether to leave this up to the consumer** _EDIT: This has to be left up to the consumer as the OAuth screen cannot be used with CORS_
- [x] Read up docs on how to implement OAuth
- [x] Read up on how to use `HttpClient` with OAuth _EDIT: Use the `Authorization: Bearer` HTTP header or the `access_token` parameter_

### 5/10/18

I've added basic OAuth 2.0 support to the demo app, although I haven't committed the changes yet.

### 6/10/18

I'm planning to try to get this in by today.

## New changes

There'll be several new parameters as part of OAuth to be implemented in `NgxYtdApiGenericProperties`:

Property | Description
---|---
`accessToken` | The access token returned from a successful authentication via Google's OAuth
