### ISSUE TITLE
[Feature] YouTube Data v3 Comments API

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/ngx-ytd-api#6]
# TODO
- [x] Read up on [docs](https://developers.google.com/youtube/v3/docs/comments)
- [x] Start work on interfaces and main code for API
- [x] Add `tsconfig`
- [ ] Add documentation
- [x] Implement OAuth (optional)
- [x] Implement [all methods](https://developers.google.com/youtube/v3/docs/comments)
  - [x] [`delete`](https://developers.google.com/youtube/v3/docs/comments/delete)
  - [x] [`insert`](https://developers.google.com/youtube/v3/docs/comments/insert)
  - [x] [`list`](https://developers.google.com/youtube/v3/docs/comments/list) (WIP)
  - [x] [`markAsSpam`](https://developers.google.com/youtube/v3/docs/comments/markAsSpam)
  - [x] [`setModerationStatus`](https://developers.google.com/youtube/v3/docs/comments/setModerationStatus)
  - [x] [`update`](https://developers.google.com/youtube/v3/docs/comments/update)
- [ ] Add API documentation
