### ISSUE TITLE
[Feature] YouTube Data v3 Comment Threads API

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/ngx-ytd-api#80]
# TODO
- [x] Read up on [docs](https://developers.google.com/youtube/v3/docs/commentThreads)
- [x] Start work on interfaces and main code for API
- [x] Add `tsconfig`
- [x] Add documentation
- [x] Implement OAuth (optional)
- [x] Implement [all methods](https://developers.google.com/youtube/v3/docs/commentThreads)
  - [x] [`insert`](https://developers.google.com/youtube/v3/docs/commentThreads/insert)
  - [x] [`list`](https://developers.google.com/youtube/v3/docs/commentThreads/list)
  - [x] [`update`](https://developers.google.com/youtube/v3/docs/commentThreads/update)
- [ ] Update roadmap
- [ ] Add tests
