### ISSUE TITLE
[Feature] YouTube Data v3 Videos API

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/ngx-ytd-api#9]
# TODO
- [x] Read up on [docs](https://developers.google.com/youtube/v3/docs/videos)
- [x] Start work on interfaces and main code for API
- [x] Add `tsconfig`
- [ ] Add documentation
- [x] Implement OAuth (optional)
- [x] Implement [all methods](https://developers.google.com/youtube/v3/docs/videos)
  - [x] [`delete`](https://developers.google.com/youtube/v3/docs/videos/delete)
  - [x] [`getRating`](https://developers.google.com/youtube/v3/docs/videos/getRating)
  - [x] [`insert`](https://developers.google.com/youtube/v3/docs/videos/insert)
  - [x] [`list`](https://developers.google.com/youtube/v3/docs/videos/list)
  - [x] [`rate`](https://developers.google.com/youtube/v3/docs/videos/rate)
  - [x] [`reportAbuse`](https://developers.google.com/youtube/v3/docs/videos/reportAbuse)
  - [x] [`update`](https://developers.google.com/youtube/v3/docs/videos/update)
- [x] Update roadmap
